### ISSUE TITLE
App doesn't work after packaging with asar

### ISSUE THREAD

**Issue by rico345100** [electron/asar#104]
I'm using electron-prebuilt v.1.4.13 and asar 0.13, using MacOS.
With electron v.1.3.x, it worked well, but using with 1.4.13, packaged app by asar doesn't run at all.
I saw that there is a file named app.asar inside of packaged app, which actually packed resources but it doesn't worked. 
Even no error message shown, just application border was slightly popped up and soon disappear.

I must use electron-prebuilt v.1.4.x, because with 1.3x, there is critical issue with my application. I don't want to give pressure to you but I'm quite busy because my application will released to public services soon, so I have to fix it as soon as possible I can.

Thanks!

**Comment by kevinsawicki** [comment]
Are you able to provide a reproduction app that demonstrates the issue?

Are you using `electron-packager` to build the asar file?

**Comment by rico345100** [comment]
@kevinsawicki Well ok, I will make a repository later. And yes, I used electron-packager.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in quite some time, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
