### ISSUE TITLE
What's the point of pickling the header_size and header?

### ISSUE THREAD

**Issue by shaggyfrog** [electron/asar#128]
Why not use a fixed 4 byte `header_size` and then read the next N bytes (`header`) as a UTF-8 string?

Was `header` pickled to accommodate different string encoding types?

What would be the reasoning to pickle a UInt32?

**Comment by zcbenz** [comment]
After a long time of maintaining different implementations of ASAR parser, I agree using Pickle is completely unnecessary.

We should change this when doing a new version of the file type.

**Comment by sploders101** [comment]
I know this is an old thread, but I'm trying to create an asar packer myself that can source files from anywhere, and make a vinyl wrapper for easy use with gulp. I was reverse-engineering the asar format and thought the same thing. Seeing that this is almost three years old, I figured I'd throw out an idea in case it helps a transition any. The first byte of the file is always a `UInt32` `4`. Considering this, we could detect a legacy vs new format in one of three ways depending on the convention used.

If we kept null-termination and ditched the length (this could complicate some things like my flexible asar implementation that supports HTTP through range requests), we could look for a `7B` in byte 0, representing a `{`, since the header is in JSON.

If we kept the length and/or ditched null termination, then the length will never be exactly 4, since `{"files":{}}` is 12 bytes, and `{}` is two. Given that the `files` prop is an essential part of the index, I don't think it will ever not be there.

We could also make those first four bytes a version ID and reserve 4 as a legacy version.

I'd imagine you've already thought of this, but I figured I'd throw it out there just in case
