### ISSUE TITLE
ELECTRON_ASAR.js:166 return old.apply(this, arguments)

### ISSUE THREAD

**Issue by dengf** [electron/asar#168]
Only on this particular user's machine, I had the following error and it cannot be replicated in any other users' machines. Thanks
`
ELECTRON_ASAR.js:166 return old.apply(this, arguments)
                   
Error: The network name cannot be found.

\\?\c:\application\resources\app.asar.unpacked\node_modules\blpapi\build\Release\blpapijs.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
`

System, electron and node details:
windows 7
node v8.14.0
electron 2.0.9
electron-builder 20.27.1

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by MarshallOfSound** [comment]
Actually can you please open this on the `electron/electron` repository.  This repository is just the `asar` packaging tooling :+1:

**Comment by dengf** [comment]
Will do and thanks
