### ISSUE TITLE
zsh: command not found: asar

### ISSUE THREAD

**Issue by CiChenEe** [electron/asar#185]
mac: 10.15.2
$ sudo npm install -g asar
/usr/local/Cellar/node/12.4.0/bin/asar -> /usr/local/Cellar/node/12.4.0/lib/node_modules/asar/bin/asar.js

asar@2.0.3
updated 1 package in 0.729s
$ asar --help
zsh: command not found: asar

**Comment by malept** [comment]
This is a problem with your shell configuration rather than an issue with `asar` itself.

Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your development environment at this time. Instead, you should consider using Stack Overflow or a similar website, as there are more people there available to answer questions.
