### ISSUE TITLE
Support for piped data

### ISSUE THREAD

**Issue by ghost** [electron/asar#21]
I've been looking into ways of creating/streaming application updates (GitHub releases) for atom-shell apps and as asar is the only real option which isn't "send all the sourcecode" I was wondering if there's any support for piped data (e.g. converting a GitHub source zip into an asar file without unextracting it onto the disk?)

**Comment by shrewdlogarithm** [comment]
I decided if I want a thing I should probably MAKE that thing so I've been trying to find ways of "piping" data to make asar files from memory (not something I've done before - not something I understand!!)

It's not easy because the existing code is heavily built around the idea of reading from the filesystem but I have a hacked demo which I'll upload here shortly - perhaps the original developer(s) could give it a look-over and we could get it integrated into this 'somehow somehow'?

I'll post back once it's uploaded...

**Comment by YuriSolovyov** [comment]
> converting a GitHub source zip into an asar file without unextracting it onto the disk

ATM, this is hardly possible(still you can create some kind of virtual disk in memory end extract there), because asar packager "walks fs" to create archive header.

But I think if you can figure out directory structure in GitHub release archive, you should be able to construct a buffer according to [asar format](https://github.com/atom/asar#format)

**Comment by AlicanC** [comment]
I stumbled upon a similiar problem when I tried to insert a [vinyl](https://github.com/wearefractal/vinyl) file using [gulp-asar](https://github.com/bwin/gulp-asar). The process actually failed at gulp-asar (which uses `asar/lib/filesystem`) and not asar itself, but it looks like asar doesn't support this anyway.

It would be great if the asar API supported some virtuality to enable reading files or directory structures virtually defined in memory and also support writing its output to memory.

**Comment by navid-zamani** [comment]
Since I needed this right now, I’ll add my solution here, in case others are trying to re-open this bug:

The problem is that there is no common format for “piping” between archives. (No idea in what format `unzip` pipes files. multipart MIME? ;) Rather **the archives themselves *are* the piping format**. So it should go the other way around!  
**There already is a common exchange format and interface: The file system!** Remember that on Unixes, everything is a file. A file system is also just a file.  
So you could just use a temporary file system. Either on disk or in RAM for extra speed, if your RAM is big enough. (Hell, if you got a FUSE implementation for it, you can use stone slabs and a stonecutter ;)

Here’s how I did it:
```bash
# /usr/bin/env bash

# parameters
source="$1" # the `zip` file
destination="$2" # the `asar` file

# settings
maxSize=1099511627776 # in bytes, uncompressed

# init
t="$(mktemp)"; mkdir "$t.d"
dd if=/dev/null bs=1 seek="$maxSize" of="$t"
mkfs.ext4 "$t"
sudo mount "$t" "$t.d" -o loop,discard
sudo chown -R "$USER:$GROUP" "$t.d"
rm -rf "$t.d/lost+found" 

# move
unzip -d "$t.d" "$source"
npx asar pack "$t.d" "$destination"

# clean up
sudo umount "$t.d"
rm -rf "$t" "$t.d"
```
• Maximum extracted size: 1TB, change the `seek=` if necessary. It creates a sparse file that only takes what’s necessary.  
• Put the mount into `/etc/fstab` with the `user` option and without using temp files, if you want to do away with the `sudo`s. This is a limitation of Unixes. Plan9 would not have that problem, thanks to namespaces. Linux may have namespace support aswell, but not as good.
• To use a ramdisk, simply use `mount -o size="$maxSize" -t tmpfs none "$t.d"` instead of the `dd`, `mkfs` and `mount`, and set maxSize to something more fitting.
