### ISSUE TITLE
`writeFileListToStream` might hang when the writable stream becomes full

### ISSUE THREAD

**Issue by weedz** [electron/asar#210]
This problem occurs when using node@15.2+ under Linux (Pop!_OS 20.10). Also tested on Mac OS 11.1 (node 15.1, 15.2 and 15.4) but no problem there. **EDIT**: Was able to reproduce this on the Mac setup. Might just be that the Macbook is to slow to trigger this problem reliably...

This might be the relevant change in node https://github.com/nodejs/node/pull/35348.

This is reproducible (at least on my machine) in my repository https://github.com/weedz/git-good. Running the command
```sh
$ npx electron-forge package
```
finishes when using node@15.1, but it hangs when using node@15.2 (also tested with version 15.4).

I then changed `writeFileListToStream` to wait for `out.writableNeedDrain` to become false. Now `electron-forge package` finishes when using node@15.2, but this could probably be solved in a better way..
```diff
+ function sleep(ms) {
+     return new Promise((resolve, reject) => setTimeout(resolve, ms));
+ }

const writeFileListToStream = async function (dest, filesystem, out, list, metadata) {
    for (const file of list) {
+       while (out.writableNeedDrain) {
+           await sleep(10);
+       }
        if (file.unpack) { // the file should not be packed into archive
            const filename = path.relative(filesystem.src, file.filename)
            await copyFile(`${dest}.unpacked`, filesystem.src, filename)
        } else {
            await streamTransformedFile(file.filename, out, metadata[file.filename].transformed)
        }
    }
    return out.end()
}
```

**Comment by weedz** [comment]
Might be a bug in Node?

Documentation for [readable.pipe()](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options) reads:

> ... The flow of data will be automatically managed so that the destination Writable stream is not overwhelmed by a faster Readable stream.

Is this still the case when piping multiple Readable streams to the same Writable stream?

**Comment by malept** [comment]
@weedz do you mind following up in the Node.js project?

**Comment by weedz** [comment]
@malept Sure

**Comment by HomerSp** [comment]
This seems to be happening for me as well when attempting to deploy https://github.com/yakyak/yakyak against node v15.4.0. It's not exactly the same I think, because randomly through the asar generating process it'll just stop and fail and not really hang - however, it also won't continue processing files in the for loop.
The workaround fixes it for me, but as you've said this really should be properly fixed in Node.js.

**Comment by weedz** [comment]
@HomerSp Looked into why it seems like `electron-forge package` hangs rather than just exiting; The cli runs a spinner in the terminal window with `packagerSpinner = ora('Packaging Application').start();`. If you comment out this line the program exits (with code 0 and without any form of errors) instead of waiting for `packagerSpinner.succeed()`.

Also ran strace on `electron-forge package`: https://gist.github.com/weedz/c856712a21881d00edfdd33043d89b8d, think this is the relevant output. I can't see any difference but I don't really know what to look for.

**Comment by HomerSp** [comment]
@weedz I've done some more testing, and I've found that ultimately the problem happens because of this change from that PR above: https://github.com/nodejs/node/pull/35348/files/3dd02b3c3c675d86c6be17b6fdb8e8994a1d65ed#diff-040c1f5a53844e600d40b33c4624f1fe39fcf2f8d62c76ca3fc5ea5442231469
Basically, when the output buffer is full the pipe opens up in a paused state, but it's never resumed which causes the problem we're seeing. If I revert just that block of code it works as expected again.
Another way to get it to work, apart from your while loop solution above is to call stream.resume after the pipe call.

Hopefully they can revert that part of the pr for the next release so it'll work as it should again.

**Comment by HomerSp** [comment]
This issue has now been fixed in https://github.com/nodejs/node/pull/36563

**Comment by weedz** [comment]
Awesome!

Closing this issue since the bug has been resolved in Node :+1:

**Comment by malept** [comment]
For the record, the affected versions of Node.js were 15.2.0 through 15.4.0 inclusive. The fix mentioned was released in Node.js 15.5.0.
