### ISSUE TITLE
Unpack then repack

### ISSUE THREAD

**Issue by jkdufair** [electron/asar#224]
When I unpack an asar file and immediately repack it, I find it repacks to a *much* larger size and it seems to be missing the `header_size` at the beginning.

```
$ npx asar --version
v2.1.0

$ ll /Applications/Microsoft\ Teams.app/Contents/Resources/app.asar
-rw-r--r--  1 root  wheel    22M Nov 10 11:19 /Applications/Microsoft Teams.app/Contents/Resources/app.asar

$ head -c 100 /Applications/Microsoft\ Teams.app/Contents/Resources/app.asar
D7@797{"files":{"assets":{"files":{".gitignore":{"size":9,"offset":"0"},"12x12-available.p%

$ npx asar extract /Applications/Microsoft\ Teams.app/Contents/Resources/app.asar ./app.unpacked

$ npx asar pack ./app.unpacked temp.asar

$ ll temp.asar
-rw-r--r--  1 jase  staff    72M Nov 10 11:22 temp.asar

$ head -c 100 temp.asar
{"files":{"assets":{"files":{".gitignore":{"size":9,"offset":"0"},"12x12-available.p%
```

Seems to occur with version 3.1.0 and even 1.0.0

**Comment by jkdufair** [comment]
Also noteworthy:

```
$ npx asar l /Applications/Microsoft\ Teams.app/Contents/Resources/app.asar > asar1.txt

$ npx asar l temp.asar > asar2.txt

$ diff asar1.txt asar2.txt

$
```

**Comment by broberson** [comment]
If there's an app.asar.unpacked directory beside your app.asar file, when you unpack it and create an app directory out of it, that directory will hold *all* of the stuff from the asar file, along with the stuff from the unpacked directory, all merged together.

When you create a new asar archive from that directory, but don't specifiy a --unpack-dir parameter, the entire contents go into the asar file, rather than being split between an asar file and an unpacked directory. The resulting file would be larger by whatever the size of that unpacked directory works out to be.

**Comment by jkdufair** [comment]
Ok thanks so much.
