### ISSUE TITLE
Save Lokijs DB in Electron

### ISSUE THREAD

**Issue by XaBerr** [electron/asar#93]
Hello,
there is some way from inside the "main.js" electron to save a file out of the asar?
I'm fighting with this command to point the way out of the write-only area but I can not do it.
It would be nice that the path was inside `/my-project/resources/` and would work even without the electron-package.
```javascript
let configFilePath = `${__dirname}/../config.json`
db = new loki(configFilePath)
if(fs.existsSync(configFilePath))
	db.loadDatabase()
```

**Comment by bengotow** [comment]
You can definitely save a file outside of your ASAR bundle. (Actually, you can't save files /inside/ the bundle, they must be outside the bundle.) For things like your app's config file, you might consider using a system-standard path instead of something relative to your application, like the Application Support directory on Mac OS X. You can look up these paths using https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname.

**Comment by XaBerr** [comment]
Ty, solved
